sudo: required

services: 
  - docker

jobs:
  include:
    # No sense in running the tests if the containers can't build!
    - stage: "Build"
      script: "docker-compose build"
    # Execute API and UI tests
    - stage: "Test"
      script: "docker-compose run --rm api ./gradlew test"
      script: "docker-compose run --rm ui npm run test"
    # Heroku deployment
    - stage: "Deploy"
      if: branch = master
      provider: heroku
      script: ./deploy.sh
