sudo: required

services: 
  - docker

language: node_js
node_js:
  - 8.5.0
script:
  - "chmod 755 ./api/gradlew && chmod 755 ./api/.gradle"
  - "docker-compose run --rm api sudo ./gradlew test"
  - "docker-compose run --rm ui npm run test"